language: node_js
node_js:
- '8'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  - DEPLOY_REPOSITORY="git@github.com:konnectors/fortuneo.git"
  # REGISTRY_TOKEN(editor=cozy, app=fortuneo)
  - secure: CQ44ZVjPAIVRvGgMcduSAX4VmaOrzF3nrJXPFUsNQ2tMVVdaAlI1zTNkdfntqigZgz6Mpk9x+2FcA8qrkNzQ4cW0lPP9f5dBtSH1xetfpXDFKprW4bqzmhgXSXJFTOYxkChOBPmCYJr+Vv4XqDkv/dBEPdfRSgvVyd5YxHSd5HBU91rKyR+Hox7LTnhmlXleLIs11EQgp7RK+L28MBCtCqAa2niFlKKRlqupm2FSpZzxCh9qeY0wKCQzPE+QZUm4waJ1SUGKQwbzAfyOxu2O6rwzaTSknfdJoSX6AMxjRTWBC9c3VfUGM3wjVJIqMhiUj2FQhVIjiDyX/W60/q3UMC5WYzSvEDDfhnKCPwiUKSU7HvSxx9q2YP34evxKo7KPahz9zLlQZvW+GBMyI9hbMDBTALuQVVzhftsvqfrogyYhkEPviiYiVADWNxhacsbUjRA5svXnZvtmCPo7fLFwel/krgC5Z8AwAY0YxWjSHNVScUkieSDCrlxrC09vTtG60unt9gtXbD5ruUkDLWSUwHBv2p0WY1TdP+2Vlf3yYfBvEVbqi59AxG+T17bq7Xv3QZnkrwC+UOCNCeg+gHPv+fRpUaYWzCO4uaoY/nlJa7RulQFhGca3A//6xRo/KgWw9JJnOXJelNjE9oHCUu9xShotUZKOF+O93V/BRqs9ITo=
  # MATTERMOST_HOOK_URL
  - secure: FY2uoT+XFjcKbOoC4Kon7q6SUz+PXQDHGNFouJriBmG72QVOgJyPMF6uLKvpXLMkUXrAGU5bq+6REhz3gymrw3EGpkIy5jOgHaHiyc0gaXtGjQzW1Tmu3VEH3o+YTAZW3/JlGZsfptqY/hiearjOJYEPrJZRFmbMGP57p0U4IOne8ZbXOzXSqmBeethUh0QDMX6HXaBArW028GZ4iz4G3lJsLZc2z0X4/wRvuzP3/3Wpgido3ycXWXYC/svWEQmPioETBxMqW//sulPtrtZfMoCAWhm9Ic7Ehoq/ZT6A3BfI24we1ddoqHwm1hWVbUoZuYFvTWzCuypfCNor39sDCCn2nnUdq07QY6+S9cFZx4Ng+th1XKAUjpmtzsqDm1Na7dkqcbG1k6821CuEMTt0vWzaihiqTgSIdOcCD3gFwvNZCYphW3vv/9nwdJgXir/CtguJO7ahsQJLTq+3Y2WeNOSUEjBkfZVku6J2vvQJFM6LL/nehB6wTZjX2hfsdyX1OowI8Zt42p1BVpuOVeQtmmu1jze+PCVExZj+cbVJPTOlUOdmhqUWOtJ50uj/3cRqmKC416Of1RBxy7ymzm6Qo7IUSruUxkF3KZRH6whdxRVnV+7/SCHoIXdgW5tyEbvySfOwsMy/a3BKizynGAs07FV/A2It+LtNtHq1FP5h5ZI=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_966557192e1a_key -iv $encrypted_966557192e1a_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
